const danceStyles = [
  'Ballet',
  'Hip-Hop',
  'Jazz',
  'Contemporary',
  'Tap Dance',
  'Ballroom Dance',
  'Latin Dance',
  'Salsa',
  'Tango',
  'Swing Dance',
  'Breakdance',
  'Bollywood Dance',
  'Street Dance',
  'Flamenco',
  'Irish Dance',
  'Belly Dance',
  'Capoeira',
  'Zumba',
  'Pole Dance',
  'African Dance',
  'High Heels',
];

export default danceStyles;
